# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.10", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      id: install-dependencies
      continue-on-error: true
      run: |
        python -m pip install --upgrade pip
        pip install --group dev
    - name: Install dependencies (old pip)
      if: steps.install-dependencies.outcome == 'failure'
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pylint black pytest
    - name: Lint with pylint
      run: |
        pylint --recursive=y --output-format=text src/ test/
    - name: Format with black
      run: |
        black --check src/ test/
    - name: Test with pytest
      run: |
        pytest
